### ISSUE TITLE
能不能单独使用其中一个评价指标呀？

### ISSUE THREAD

**Issue by 18166035475** [exe1023/DialEvalMetrics#1]
比如我想单独直接使用ADEM，运行ADEM里面的eval.py

**Comment by exe1023** [comment]
可以，有兩種方法

第一種是直接修改eval_metrics.sh，將想使用的metric以外的指令全部都comment掉。
這個作法適用於想測試一個metric在多個dataset上，或是新加入一個metric只想要測試它時
第二種是直接輸入eval_metrics.sh裡面對應metric的command。
以ADEM為例，它被implemented在baseline裡面，所以是進入eval_base的conda env後輸入:
`python baseline_metric.py --data $data`

**Comment by 18166035475** [comment]
好的，感谢
