### ISSUE TITLE
conda install:Found conflicts! Looking for incompatible packages.

### ISSUE THREAD

**Issue by zperfet** [exe1023/DialEvalMetrics#2]
when i run "conda env update --name eval_base --file conda_envs/eval_base/environment.yml" on mac,
error reports :
Collecting package metadata (repodata.json): done
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (libgcc-ng):

**Comment by exe1023** [comment]
I have updated the environment.yml and installation instructions. Could you try again?
