### ISSUE TITLE
Unable to find "run_eval.sh"

### ISSUE THREAD

**Issue by liuzeming01** [exe1023/DialEvalMetrics#4]
Modify the path in run_eval.sh as specified in the script, since we need to activate Conda environment when running the script. Run eval_metrics.sh to evaluate all quality-anntoated data.
________________________________________________________________________________________________________________________

I can't find "run_eval.sh". Who knows where it is？

**Comment by exe1023** [comment]
run_eval.sh is placed in the directory of metrics
